name: Roy Ledford
markdown: kramdown
highlighter: rouge # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json", "Design Docs"]
include: ["_tags"]
# permalink: /:title/

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-sitemap
  